### GET admin all
GET localhost:8082/admin/api/v1/get-all-admin
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJkaXlvcmJla3Nob2Rtb25vdjIwMDJAZ21haWwuY29tIiwicm9sZXMiOiJTVVBFUl9BRE1JTiIsImlkIjoiMSIsImlhdCI6MTc1NzU3NTI0MiwiZXhwIjoxNzU3NjYxNjQyfQ.YZ1ZBWJBWqZRRpbsvELchNro0_JbJ2fDcIKG56oYUxBP3e-77Y67O26LHa_wjoG5wl3DXN-ZiNmulFVtV9JzJQ

### GET admin by id
GET localhost:8082/admin/api/v1/get-admin?id=2
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJkaXlvcmJla3Nob2Rtb25vdjIwMDJAZ21haWwuY29tIiwicm9sZXMiOiJTVVBFUl9BRE1JTiIsImlkIjoiMSIsImlhdCI6MTc1NzU3NTI0MiwiZXhwIjoxNzU3NjYxNjQyfQ.YZ1ZBWJBWqZRRpbsvELchNro0_JbJ2fDcIKG56oYUxBP3e-77Y67O26LHa_wjoG5wl3DXN-ZiNmulFVtV9JzJQ

### delete admin
DELETE localhost:8082/admin/api/v1/delete?id=3
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJkaXlvcmJla3Nob2Rtb25vdjIwMDJAZ21haWwuY29tIiwicm9sZXMiOiJTVVBFUl9BRE1JTiIsImlkIjoiMSIsImlhdCI6MTc1NzU3NTI0MiwiZXhwIjoxNzU3NjYxNjQyfQ.YZ1ZBWJBWqZRRpbsvELchNro0_JbJ2fDcIKG56oYUxBP3e-77Y67O26LHa_wjoG5wl3DXN-ZiNmulFVtV9JzJQ
